version: '3.8'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - llm-network

  redisinsight:
    image: redis/redisinsight
    container_name: redis-insight
    ports:
      - "5540:5540"
    networks:
      - llm-network
    links:
      - redis # Allows RedisInsight to connect to the Redis service by name

  ollama:
    image: ollama/ollama
    container_name: ollama-simple
    ports:
      - "11434:11434"
    networks:
      - llm-network
    # restart: unless-stopped
    # entrypoint: ["/bin/bash", "-c", "
    #   ollama serve & 
    #   sleep 5 
    #   ollama pull llama3.2 
    #   wait"]

  server:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - redis
      - redisinsight
      - ollama
    networks:
      - llm-network

networks:
  llm-network:
    driver: bridge